### ISSUE TITLE
Not working for DynamoDB tables with sortKey

### ISSUE THREAD

**Issue by ppm-soumya** [tristanls/dynamodb-lock-client#24]
Not working for DynamoDB tables with sortKey. There is no option to provide sort_key which is resulting into mismatch of schema while acquiring lock.

```
ERROR	ValidationException: The provided key element does not match the schema
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18
```

**Comment by tristanls** [comment]
That's correct. The design assumes a table exists exclusively for locking use and is set up in a manner described [here](https://github.com/tristanls/dynamodb-lock-client#setting-up-the-lock-table-in-dynamodb).

**Comment by tristanls** [comment]
With release of [v0.7.1](https://github.com/tristanls/dynamodb-lock-client/releases/tag/v0.7.1), sort key is now supported.
